kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        apiVersion: kubeadm.k8s.io/v1beta2
        kind: ClusterConfiguration
        metadata:
          name: config
        apiServer:
          extraArgs:
            enable-admission-plugins: NodeRestriction,PodSecurityPolicy
            "feature-gates": "DynamicAuditing=true"
        scheduler:
          extraArgs:
            "feature-gates": "DynamicAuditing=true"
        controllerManager:
          extraArgs:
            "feature-gates": "DynamicAuditing=true"
      # To make sure that there is no taint for master node.
      # Otherwise additional worker node might be required for conformance testing.
      - |
        apiVersion: kubeadm.k8s.io/v1beta2
        kind: InitConfiguration
        nodeRegistration:
          taints: []
  - role: worker
networking:
  disableDefaultCNI: true
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.245.0.0/16"
