apiVersion: v1
name: operator
home: https://cilium.io/
version: 1.7.90
appVersion: 1.7.90
tillerVersion: ">=2.7.2"
description: Helm chart for cilium-operator deployment
keywords:
sources:
  - https://github.com/cilium/cilium
engine: gotpl
