name: Documentation Updates

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  build-html:
    name: Validate & Build HTML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Building htlm site
        run: |
          make -C Documentation default

  docs-check:
    name: Validate and Check cmdref and examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run make check
        run: |
          make -C Documentation check
          git diff --exit-code
