name: Go-related checks

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  go-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check module vendoring
        run: |
          go mod tidy
          go mod vendor
          git diff --exit-code

  generate-k8s-api:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.2
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # hard-code the path instead of using ${{ github.repository }} to make sure it works for fork repo as well
          path: src/github.com/cilium/cilium
      - name: Install protobuf dependencies
#        env:
#          PROTOBUF_VERSION: 3.0.0-9.1ubuntu1
        run: |
          sudo apt install -y protobuf-compiler libprotobuf-dev
      - name: Set GOPATH
        run: |
          echo "##[set-env name=GOPATH;]$GITHUB_WORKSPACE"
        shell: bash
      - name: Check k8s generated files
        run: |
          dpkg -s protobuf-compiler | grep Version

          cd src/github.com/cilium/cilium
          contrib/scripts/check-k8s-code-gen.sh
