name: Smoke test

on:
  pull_request: {}
  push:
    branches:
      - master

env:
  KIND_VERSION: v0.8.1
  KIND_CONFIG: .github/kind-config.yaml
  QUICK_INSTALL_FILE: install/kubernetes/quick-install.yaml
  EXP_INSTALL_FILE: install/kubernetes/experimental-install.yaml
  CONNECTIVITY_CHECK_FILE: examples/kubernetes/connectivity-check/connectivity-check.yaml

jobs:
  preflight-clusterrole:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check pre-flight clusterrole
        run: |
          cd install/kubernetes/cilium/charts
          echo "Checking for differences between preflight and agent clusterrole"
          diff \
             -I '^[ ]\{2\}name: cilium.*' \
             -I '^Keep file in synced with.*' \
             agent/templates/clusterrole.yaml \
             preflight/templates/clusterrole.yaml

  quick-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check quick-install.yaml
        run: |
          make -C install/kubernetes quick-install
          git diff --exit-code

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0-rc.1
        with:
          version: ${{ env.KIND_VERSION }}
          config: ${{ env.KIND_CONFIG }}

      - name: Run quick install
        run: |
          kubectl apply -f $QUICK_INSTALL_FILE
          kubectl wait -n kube-system --for=condition=Available --all pod --timeout=300s

      - name: Run conformance test (e.g. connectivity check)
        run: |
          kubectl apply -f $CONNECTIVITY_CHECK_FILE
          kubectl wait --for=condition=Available --all deployment --timeout=300s

  experimental-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check experimental-install.yaml
        run: |
          make -C install/kubernetes experimental-install
          git diff --exit-code

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0-rc.1
        with:
          version: ${{ env.KIND_VERSION }}
          config: ${{ env.KIND_CONFIG }}

      - name: Run experimental install
        run: |
          kubectl apply -f $EXP_INSTALL_FILE
          kubectl wait -n kube-system --for=condition=Available --all pod --timeout=300s

      - name: Run conformance test (e.g. connectivity check)
        run: |
          kubectl apply -f $CONNECTIVITY_CHECK_FILE
          kubectl wait --for=condition=Available --all deployment --timeout=300s

  conformance-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run helm lint
        run: |
          cd install/kubernetes/cilium
          helm lint --with-subcharts --values values.yaml

      - name: Build docker images
        run: |
          make docker-image-no-clean
          make docker-operator-generic-image

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0-rc.1
        with:
          version: ${{ env.KIND_VERSION }}
          config: ${{ env.KIND_CONFIG }}

      - name: Load local images into kind cluster
        run: |
          kind load docker-image cilium/cilium:latest
          kind load docker-image cilium/operator-generic:latest

      - name: Install cilium chart
        run: |
          helm install cilium ./install/kubernetes/cilium \
             --wait \
             --namespace kube-system \
             --set global.nodeinit.enabled=true \
             --set global.kubeProxyReplacement=partial \
             --set global.hostServices.enabled=false \
             --set global.externalIPs.enabled=true \
             --set global.nodePort.enabled=true \
             --set global.hostPort.enabled=true \
             --set global.pullPolicy=Never
      - name: Run conformance test (e.g. connectivity check)
        run: |
          kubectl apply -f $CONNECTIVITY_CHECK_FILE
          kubectl wait --for=condition=Available --all deployment --timeout=300s