name: Smoke test

on:
  pull_request: {}
  push:
    branches:
      - master
env:
  KIND_VERSION: v0.9.0
  KIND_CONFIG: .github/kind-config.yaml
  CONFORMANCE_TEMPLATE: examples/kubernetes/connectivity-check/connectivity-check.yaml
  TIMEOUT: 2m
  LOG_TIME: 30m

jobs:
  conformance-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Precheck generated connectivity manifest files
        run: |
          make -C examples/kubernetes/connectivity-check fmt
          make -C examples/kubernetes/connectivity-check all
          git diff --exit-code

#      - name: Build docker images
#        run: |
#          make docker-cilium-image
#          make docker-operator-generic-image

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
        with:
          version: ${{ env.KIND_VERSION }}
          config: ${{ env.KIND_CONFIG }}

#      - name: Load local images into kind cluster
#        run: |
#          kind load docker-image --name chart-testing cilium/cilium:latest
#          kind load docker-image --name chart-testing cilium/operator-generic:latest

      - name: Install cilium chart
        run: |
          helm install cilium ./install/kubernetes/cilium \
             --wait \
             --namespace kube-system \
             --set global.debug.enabled=true \
             --set global.nodeinit.enabled=true \
             --set global.kubeProxyReplacement=partial \
             --set global.hostServices.enabled=false \
             --set global.externalIPs.enabled=true \
             --set global.nodePort.enabled=true \
             --set global.hostPort.enabled=true \
             --set config.bpfMasquerade=false \
             --set config.ipam=kubernetes \
             --set global.prometheus.enabled=true \
             --set global.operatorPrometheus.enabled=true \
             --set global.hubble.enabled=true \
             --set global.hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,http}"

          kubectl wait -n kube-system --for=condition=Ready --all pod --timeout=5m
          # To make sure that cilium CRD is available (default timeout is 5m)
          # https://github.com/cilium/cilium/blob/master/operator/crd.go#L34
          kubectl wait --for condition=Established crd/ciliumnetworkpolicies.cilium.io --timeout=5m

      - name: Run conformance test (e.g. connectivity check)
        run: |
          kubectl apply -f ${{ env.CONFORMANCE_TEMPLATE }}
          kubectl wait --for=condition=Available --all deployment --timeout=${{ env.TIMEOUT }}

      - name: Get coredns log
        if: ${{ failure() }}
        run: |
          kubectl log -n kube-system deployment/coredns

      - name: Capture cilium-sysdump
        if: ${{ failure() }}
        run: |
          curl -sLO https://github.com/cilium/cilium-sysdump/releases/latest/download/cilium-sysdump.zip
          python cilium-sysdump.zip --output cilium-sysdump-out

      - name: Upload cilium-sysdump
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: cilium-sysdump-out.zip
          path: cilium-sysdump-out.zip